const Images = [
  {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },
   {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/first.jpg"
  },
  {
    title:'image',
    imageUrl:"/images/second.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/third.jpg"
  },
    {
    title:'image',
    imageUrl:"/images/fourth.jpg"
  },

]
export default Images;